In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("/content/fraud_transactions_synthetic.csv")

In [3]:
data.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score,is_fraud
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327,0
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084,0
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303,0
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368,0
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630,1

In [4]:
data.isna().sum()

amount                 0
hour                   0
distance_km            0
failed_logins_24h      0
is_international       0
is_new_device          0
account_age_days       0
txn_velocity_1h        0
prev_chargebacks       0
merchant_risk_score    0
is_fraud               0
dtype: int64

In [5]:
data.info()
#we have 10 input features - we will have to have 10 neurons in the Input layer of the NN
#we have 1 output feature

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   amount               40000 non-null  float64
 1   hour                 40000 non-null  int64
 2   distance_km          40000 non-null  float64
 3   failed_logins_24h    40000 non-null  int64
 4   is_international     40000 non-null  int64
 5   is_new_device        40000 non-null  int64
 6   account_age_days     40000 non-null  int64
 7   txn_velocity_1h      40000 non-null  int64
 8   prev_chargebacks     40000 non-null  int64
 9   merchant_risk_score  40000 non-null  float64
 10  is_fraud             40000 non-null  int64
dtypes: float64(3), int64(8)
memory usage: 3.4 MB

In [6]:
import tensorflow as tf
from tensorflow import keras #one of the most important modules in tensorflow
from tensorflow.keras import layers #layers will help us in building the neural ntwork sequentially

In [7]:
x=data.drop(['is_fraud'],axis=1) #all the input independent columns
y=data['is_fraud'] #output dependent column

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

In [9]:
x_train.shape[1] #these 10 neurons will be used in the input layer when we build our NN

10

In [12]:
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'),
    layers.Dense(16,activation='relu',name='hidden_layer_1'),#number of neurons in the 1st hidden layer - 16 neurons
    layers.Dense(32,activation='relu',name='hidden_layer_2'),#number of neurons in the 2nd hidden layer - 32 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #number of neurons in the output layer -1 and sigmoid af since it is a case of binary classification
])

Task: Observe the difference in output accuracy basis the following:

- Increase the number of epochs from 10 to 20
- change the activation function from relu to tanh in both the hidden layers
- change the activation function from relu to tanh in 1st hidden layer and keep it same for the 2nd hidden layer
- change the activation function from sigmoid to - first relu then softmax then tanh in the output layer

In [13]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy', #binary_crossentropy is used for binary classification [sparse_categorical_crossentropy - for multiclass classification]
    metrics=['accuracy']
)

In [14]:
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9342 - loss: 0.3475
Epoch 2/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9385 - loss: 0.2945
Epoch 3/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9393 - loss: 0.2715
Epoch 4/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9397 - loss: 0.2655
Epoch 5/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9388 - loss: 0.2729
Epoch 6/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9394 - loss: 0.2677
Epoch 7/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9395 - loss: 0.2642
Epoch 8/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9398 - loss: 0.2526
Epoch 9/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9402 - loss: 0.2519
Epoch 10/10
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9406 - loss: 0.2434